Zy/212 gui r scripts finish popup
gjwgit/rattle pull request #370
Opened 2024-08-29 03:00 UTC by zheyxu

# Pull Request Details

## What issue does this PR address

- GUI: After R scripts finish popup a SnackBar to say the plot generation is completed.

- Link to associated issue: #212 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added a reviewer

## Finalising

Once PR discussion is complete and reviewer has approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

2024-08-29 10:33 UTC, gjwgit requested changes
Not sure I like this solution. I need to modify every script I write and that is a maintenance nightmare.

2024-08-29 10:33 UTC, gjwgit commented on assets/r/explore_summary.R
> +print("Execution Completed")
Please fix up the end of file - missing new line.

2024-08-29 10:33 UTC, gjwgit commented on lib/r/source.dart
> +  // Optionally, show a SnackBar when the script starts executing.
Should this be showing the message when the script finished, not when it starts?

2024-08-30 07:14 UTC, Lutra-Fs reviewed
As we are currently facing the execution order problem, should we better include which file/function are completed?

2024-08-31 08:35 UTC, zheyxu commented
> As we are currently facing the execution order problem, should we better include which file/function are completed?
Included:
<img width="1249" alt="Screenshot 2024-08-31 at 6 34 38 PM" src="https://github.com/user-attachments/assets/5444ac33-fc1a-4345-a694-cb55f9c17ce0">

2024-09-02 03:14 UTC, gjwgit commented
Closing this PR as the solution is not efficient. The related issue moved back to In Progress. This might also be relevant to the async RScript redesign.

2024-09-02 03:14 UTC, closed without merging