Zy/201 bug visual images remains after reset
gjwgit/rattle pull request #381
Opened 2024-09-03 11:16 UTC by zheyxu

# Pull Request Details

## What issue does this PR address

- bug visual images remains after reset

- Link to associated issue: #201

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added a reviewer

## Finalising

Once PR discussion is complete and reviewer has approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

2024-09-03 23:14 UTC, gjwgit commented on integration_test/utils/navigator_to_page.dart
Wrong file name.

2024-09-03 23:15 UTC, gjwgit commented on integration_test/utils/navigator_to_page.dart
> +/// Copyright (C) 2023-2024, Togaware Pty Ltd
Years should be 2024, not 2023-2024 - this file did not exist in 2023.

2024-09-03 23:16 UTC, gjwgit commented on integration_test/dataset_demo_reset_image_test.dart
> +/// Copyright (C) 2023-2024, Togaware Pty Ltd
Copyright date should be 2024.

2024-09-03 23:20 UTC, gjwgit requested changes

2024-09-03 23:20 UTC, gjwgit commented on lib/features/tree/display.dart
> +    if (content.isNotEmpty) {
How does this make sense? We have a general problem across the app with managing the image files and how to know they have been properly updated. I don't think this solves the issue? Explain how this fixes that issue?

2024-09-04 03:47 UTC, zheyxu commented on integration_test/utils/navigator_to_page.dart
Thanks! But I don't know the correct name. Can you change it @gjwgit?

2024-09-04 03:54 UTC, gjwgit commented on lib/widgets/image_page.dart
> -                    // 20240726 gjw Ensure the Save button is aligned at the
Keep this comment.

2024-09-04 03:59 UTC, gjwgit requested changes
I am getting some odd behaviour.

Do the tests work for you?

2024-09-04 04:00 UTC, zheyxu commented
Works for me.

2024-09-04 04:06 UTC, gjwgit commented
When I run `make dataset_demo_reset_image.qtest` I see the following error repeated over and over:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test (but after the test had completed):
Bad state: Tried to read a provider from a ProviderContainer that was already disposed

When the exception was thrown, this was the stack:
#0      ProviderContainer.readProviderElement (package:riverpod/src/framework/container.dart:423:7)
#1      ProviderElementProxy.read (package:riverpod/src/framework/proxy_provider_listenable.dart:129:26)
#2      ProviderContainer.read (package:riverpod/src/framework/container.dart:241:21)
#3      ProviderElementBase.read (package:riverpod/src/framework/element.dart:675:23)
#4      ptyProvider.<anonymous closure>.<anonymous closure> (package:rattle/providers/pty.dart:54:9)
#15     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#16     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#17     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#18     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#19     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#27     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#39     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 28 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

2024-09-05 02:01 UTC, junhaow1 commented
Hi @gjwgit  , flutter test integration_test/dataset_demo_reset_image_test.dart is working on my machine 
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/91137dea-ff76-4015-b605-c5afb85ac8cc">

2024-09-05 02:04 UTC, junhaow1 commented
make dataset_demo_reset_image.qtest is working as well 
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/61efc7ae-b3b5-46fb-9dca-a7a260aac4c8">

2024-09-06 20:19 UTC, gjwgit approved these changes

2024-09-06 20:19 UTC, gjwgit commented on integration_test/utils/navigator_to_page.dart
The function name is navigateToPage() So the file name is navigate_to_page.dart? That should be clear?

2024-09-06 20:23 UTC, gjwgit approved these changes

2024-09-06 20:23 UTC, merged