kev/341_delete_helper_rename_util_functions
gjwgit/rattle pull request #406
Opened 2024-09-09 06:22 UTC by junhaow1

# Pull Request Details

## What issue does this PR address

- delete helper.dart file and rename util functions

- Link to associated issue: #341 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added a reviewer

## Finalising

Once PR discussion is complete and reviewer has approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

2024-09-09 06:23 UTC, junhaow1 commented
To keep this PR focus on renaming the functions, next PR will focus on impute testing alone

2024-09-09 20:08 UTC, gjwgit requested changes

2024-09-09 20:08 UTC, gjwgit commented on integration_test/utils/navigate_to_tab.dart
Lots of repeated code here. DRY. Couldn't you have a structure like [{'tab': 'Explore', 'icon': Icons.insights, 'type': ExploreTabs}, ...] (as a first guess) and have a single body, and be sure to cover all tabs?

2024-09-09 23:09 UTC, junhaow1 commented on integration_test/utils/navigate_to_tab.dart
on it

2024-09-09 23:24 UTC, junhaow1 commented on integration_test/utils/navigate_to_tab.dart
eliminates repeated if-else conditions : 
<img width="914" alt="image" src="https://github.com/user-attachments/assets/7790994c-4a07-4a87-90db-413535d02349">

2024-09-10 06:02 UTC, gjwgit approved these changes
Nicely done. Thanks @junhaow1.

I added some pauses for timing of the itest.

2024-09-10 06:23 UTC, zheyxu approved these changes

2024-09-10 06:25 UTC, merged