Yyx/327 test sherlock
gjwgit/rattle pull request #436
Opened 2024-09-18 09:54 UTC by yixiangyin

# Pull Request Details

## What issue does this PR address

- [A one line description of this PR]

- Link to associated issue: #

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] No integrated test errors
- [ ] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

2024-09-18 19:32 UTC, gjwgit requested changes
Basic load datasaet test. Thanks. 

Please split openDatsetByPath to open_dataset_by_path.dart.

2024-09-18 19:32 UTC, gjwgit commented on integration_test/utils/open_large_dataset.dart
I prefer one file per function.

2024-09-19 22:04 UTC, gjwgit reviewed
I had to update to get it to work. Was this tested at all? 

Also non-conforming to style requirements.

Cleaned up coding.

Running `make qtest.tmp` to test before merge.

2024-09-20 02:29 UTC, gjwgit approved these changes

2024-09-20 04:55 UTC, merged

2024-09-21 07:55 UTC, yixiangyin commented
> I had to update to get it to work. Was this tested at all?
> 
> Also non-conforming to style requirements.
> 
> Cleaned up coding.
> 
> Running `make qtest.tmp` to test before merge.

@gjwgit This is a **draft** PR only. I haven't made it actual PR because it's not ready to be merged yet.