Kev/413_page
gjwgit/rattle pull request #483
Opened 2024-09-27 00:03 UTC by junhaow1

# Pull Request Details

## What issue does this PR address

- DATASET: After BUILD go to the second page. #413

- Link to associated issue: #413 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [ ] Tested on device:
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

2024-09-27 00:14 UTC, gjwgit commented
Fails on first try of loading a dataset?

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 157 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:157:12)
#3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:191:41)
#4      DatasetPopup.build.<anonymous closure> (package:rattle/features/dataset/popup.dart:169:52)
<asynchronous suspension>
```

2024-09-29 20:22 UTC, gjwgit requested changes
Blocked until it is manually tested as working.

- [ ] DEMO -> results in above exception and no navigation to ROLES page
- [x] EXPLORE -> SUMMARY -> BUILD navigates to SUMMARY page
- [x] VISUAL -> BUILD navigates to BOX PLOT
- [ ] CORRELATION -> BUILD dose not navigate the first time but does on a second BUILD

2024-09-29 22:03 UTC, gjwgit requested changes

2024-09-29 22:03 UTC, gjwgit commented on support/flutter.mk
Why is this reverting a dev update? It should be INTERACT not PAUSE no. That was updated a little while ago.

2024-09-29 22:22 UTC, junhaow1 commented on support/flutter.mk
This Makefile rule change aimed to fix the Xcode warnings on macOS ('make qtest.tmp command'), now replacing PAUSE with INTERACT.

2024-09-29 22:45 UTC, gjwgit commented on support/flutter.mk
Thanks for the explanation. Yes, I think redirecting stderr to /dev/null makes sense.

2024-09-30 02:23 UTC, gjwgit approved these changes

2024-09-30 02:24 UTC, merged