Kev/490_remain
gjwgit/rattle pull request #496
Opened 2024-10-04 04:20 UTC by junhaow1

# Pull Request Details

## What issue does this PR address

- NAVIGATION: Remain on current page after a BUILD except if on page 0 #490

- Link to associated issue: #490 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [ ] Tested on device:
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

2024-10-04 04:23 UTC, junhaow1 commented
<img width="627" alt="image" src="https://github.com/user-attachments/assets/bddf08e7-3f2e-4af3-8b70-24a3cdba66fa">

2024-10-04 20:21 UTC, gjwgit commented on lib/widgets/activity_button.dart
Why not call it onPressed rather than additionalLogic?

2024-10-04 20:42 UTC, gjwgit requested changes
Need a walk through on this to clarify the thinking.

2024-10-04 20:42 UTC, gjwgit commented on lib/utils/page_navigation_logic.dart
Where is this used?

2024-10-06 00:45 UTC, gjwgit approved these changes

2024-10-06 00:45 UTC, gjwgit commented on lib/widgets/activity_button.dart
> +                (currentPage >= 2 && currentPage <= 4) ? currentPage : 1;
Why less than 4?

2024-10-06 00:45 UTC, merged