Zy/143 xgboost
gjwgit/rattle pull request #498
Opened 2024-10-05 01:14 UTC by zheyxu

# Pull Request Details

## What issue does this PR address

- XGBOOST: Add support for XGBoost trees and tuning

- Link to associated issue: #143 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [ ] Tested on device:
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

2024-10-05 21:09 UTC, gjwgit requested changes

2024-10-05 21:09 UTC, gjwgit commented on assets/r/model_build_adaboost.R
This is odd? For example, `target` is *not* usually a column in the dataset. The model build is a perfect model because the input variable rain_tomorrow is the output variable that seems to have been created and called target. The results are very wrong!

2024-10-08 06:18 UTC, gjwgit requested changes

2024-10-08 06:18 UTC, gjwgit commented on lib/features/boost/config.dart
> +              onPressed: () async {
Need to also pass the pageControllerProvider to the ActivityButton so we get the NextPage behaviour after pressing the button.

2024-10-08 10:04 UTC, gjwgit requested changes

2024-10-08 10:04 UTC, gjwgit commented on lib/features/boost/boost_setting.dart
Please rename this to just `settings.dart` - having boost twice (the folder name) is redundant.

2024-10-08 10:04 UTC, gjwgit commented on lib/features/boost/boost_setting.dart
> +            variableChooser(
Could you add a tooltip here in the same style as our other tooltips. We seem not to have any tooltips for our variable choosers in the app so far. Time to fix that! Thanks.

2024-10-08 15:04 UTC, zheyxu commented on lib/features/boost/boost_setting.dart
Done

2024-10-09 05:59 UTC, gjwgit approved these changes

2024-10-09 05:59 UTC, gjwgit commented on lib/widgets/number_field.dart
Tested - works well. Thanks.

2024-10-09 05:59 UTC, gjwgit commented on lib/features/boost/display.dart
Need to migrate to using pageViewer.

2024-10-09 05:59 UTC, merged