Zy/477 cluster implement ewkm
gjwgit/rattle pull request #506
Opened 2024-10-10 02:44 UTC by zheyxu

# Pull Request Details

## What issue does this PR address

- CLUSTER: Implement EWKM

- Link to associated issue: #477

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [ ] Tested on device:
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

2024-10-11 20:00 UTC, gjwgit commented
Looks good - I will test run and review code.

2024-10-12 07:52 UTC, gjwgit commented on assets/r/model_build_cluster_kmeans.R
> +library(wskm, quietly=TRUE)  # Load the wskm package for EWKM
Is wskm required for kmeans?

2024-10-12 08:18 UTC, gjwgit requested changes
Please review my updates. Thanks.

2024-10-12 11:40 UTC, zheyxu reviewed
Checked.

2024-10-12 18:23 UTC, merged