kev/515_impute
gjwgit/rattle pull request #523
Opened 2024-10-14 23:22 UTC by junhaow1

…tant TextField

# Pull Request Details

## What issue does this PR address

- IMPUTE: Constant text field only accessible when CONSTANT enabled #515

- Link to associated issue: #515 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [ ] Tested on device:
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

2024-10-15 03:28 UTC, gjwgit requested changes
Please use out standard widgets/DelayedTooltip widget so all tooltips are the same style and behaviour. Also see my note that you delted that requests

  // TODO 20240810 gjw USE CHOICE CHIP TIP

Was there a problem with that?

2024-10-15 03:32 UTC, junhaow1 commented
> Please use out standard widgets/DelayedTooltip widget so all tooltips are the same style and behaviour. Also see my note that you delted that requests
> 
> // TODO 20240810 gjw USE CHOICE CHIP TIP
> 
> Was there a problem with that?

on it

2024-10-15 23:13 UTC, gjwgit requested changes

2024-10-15 23:13 UTC, gjwgit commented on lib/features/impute/config.dart
> +  // TODO 20240810 gjw USE CHOICE CHIP TIP
Why not ChoiceChipTip()?

2024-10-15 23:19 UTC, gjwgit commented
Please add extra space between the Mode and the Constant chips.

2024-10-15 23:20 UTC, gjwgit commented
How come I see the default is 0 for this categoric variable

![image](https://github.com/user-attachments/assets/d3dd9f93-85de-4fa7-91f3-ecd7c9a7e54f)

2024-10-16 21:52 UTC, gjwgit approved these changes

2024-10-16 21:52 UTC, merged